---
- name: vpc subnet and instance
  hosts: localhost
  connection: local
  gather_facts: no


  collections:
    - amazon.aws


  tasks:
  

    - name: create vpc
      amazon_vpc_net:
        name: my-vpc
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
      register: vpc

  

    - name: create subnet
      amazon_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr}}"
        az: "{{ region }}a"
        region: "{{ region }}"
      register: subnet


    - name: launch ec2 instance
      amazon.aws.ec2_instance:
        name: bare-instance
        key_name: "{{key_name}}"
        region: "{{region}}"
        image_id: "{{ami_id}}"
        instance_type: "{{instance_type}}"
        vpc_subnet_id: "{{subnet.subnet.id}}"
        wait: yes
      register: ec2


    - name: show instance id
      debug:
        msg: "ec2 instance id: {{ec2.instances[0].instance_id}}"
